# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import todo_pb2 as todo__pb2


class ToDoStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTodo = channel.unary_unary(
                '/todo.ToDo/getTodo',
                request_serializer=todo__pb2.GetToDoRequest.SerializeToString,
                response_deserializer=todo__pb2.Todo.FromString,
                )
        self.searchTodos = channel.unary_unary(
                '/todo.ToDo/searchTodos',
                request_serializer=todo__pb2.Null.SerializeToString,
                response_deserializer=todo__pb2.TodoSearchResult.FromString,
                )


class ToDoServicer(object):
    """The greeting service definition.
    """

    def getTodo(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToDoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.getTodo,
                    request_deserializer=todo__pb2.GetToDoRequest.FromString,
                    response_serializer=todo__pb2.Todo.SerializeToString,
            ),
            'searchTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.searchTodos,
                    request_deserializer=todo__pb2.Null.FromString,
                    response_serializer=todo__pb2.TodoSearchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todo.ToDo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ToDo(object):
    """The greeting service definition.
    """

    @staticmethod
    def getTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.ToDo/getTodo',
            todo__pb2.GetToDoRequest.SerializeToString,
            todo__pb2.Todo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def searchTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.ToDo/searchTodos',
            todo__pb2.Null.SerializeToString,
            todo__pb2.TodoSearchResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
